builds:
  - id: meteor
    main: .
    binary: meteor
    flags:
      - "--trimpath"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - "386"
      - amd64
      - arm64
archives:
  -
    format: binary
    name_template: "{{ .Binary}}-{{ .Os }}-{{ .Arch }}"
brews:
  - name: meteor
    homepage: https://github.com/stefanlogue/homebrew-tools
    repository:
      owner: stefanlogue
      name: homebrew-tools
release:
  prerelease: auto
  github:
    owner: stefanlogue
    name: meteor

