name: PR pipeline

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.1
      - name: Install dependencies
        run: go get .
      - name: build
        run: go build -v ./...
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.1
      - name: Install dependencies
        run: go get .
      - name: test
        run: go test -json > test-results.json
      - name: upload results
        uses: actions/upload-artifact@v4
        with:
          name: meteor-TestResults
          path: meteor-TestResults.json
